### ISSUE TITLE
luci-app-qbittorrent能否换源，更新后的选项太多操作繁琐。路由重启后每次的覆盖我配置文件。

### ISSUE THREAD

**Issue by lfergober** [linkease/istore-packages#25]
luci-app-qbittorrent能否换源，更新后的选项太多操作繁琐。路由重启后每次的覆盖我配置文件。
网友推荐 https://github.com/immortalwrt/luci/tree/openwrt-21.02/applications/luci-app-qbittorrent 能否替换？

**Comment by lfergober** [comment]
另外请问 https://github.com/linkease/istore-packages/tree/main/luci-app-fileassistant 这个插件好像iStore里搜不到啊？

**Comment by jjm2473** [comment]
qb之前的luci有bug，会导致语言错误，还有临时文件错误，今晚更新以后应该就没问题了。大部分qb的配置都不会被启动脚本修改的。

文件助手一般都集成到固件里了，所以没上架。
