### ISSUE TITLE
luci-app-zerotier 版本 v1.1.1-1 中 zerotier-one `zerotier-cli` 相关命令使用变得困难

### ISSUE THREAD

**Issue by zctmdc** [linkease/istore-packages#31]
尊敬的开发者您好：

## 问题描述

在 [commit 3874e89](https://github.com/linkease/istore-packages/commit/3874e89f84c2036227ffb12007d12ba87befa188) 中修改了文件 [`luci-app-zerotier/root/etc/init.d/luci_zerotier` 第八行 ](https://github.com/linkease/istore-packages/blob/3874e89f84c2036227ffb12007d12ba87befa188/luci-app-zerotier/root/etc/init.d/luci_zerotier#L8) 中 `zerotier-one` 配置路径变量 `CONFIG_PATH`

```
- CONFIG_PATH=/var/lib/zerotier-one
+ CONFIG_PATH=/var/lib/zerotier-luci
```

这使得 `zerotier-cli` 相关命令使用变得困难，其表现为：

```shell
root@EH-OPx86:~# zerotier-cli info
zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one
```

```shell
root@EH-OPx86:~# zerotier-one -h
ZeroTier One version 1.12.1
Copyright (c) 2020 ZeroTier, Inc.
Licensed under the ZeroTier BSL 1.1 (see LICENSE.txt)
Usage: zerotier-one [-switches] [home directory]

Available switches:
  -h                - Display this help
  -v                - Show version
  -U                - Skip privilege check and do not attempt to drop privileges
  -p<port>          - Port for UDP and TCP/HTTP (default: 9993, 0 for random)
  -d                - Fork and run as daemon (Unix-ish OSes)
  -i                - Generate and manage identities (zerotier-idtool)
  -q                - Query API (zerotier-cli)
root@EH-OPx86:~# zerotier-one -q
zerotier-one: missing port and zerotier-one.port not found in /var/lib/zerotier-one
```

## 问题原因

`zerotier-cli` 默认使用 `/var/lib/zerotier-one` 路径作为 *ZeroTier home path*

## 解决办法

1. 在使用 `zerotier-cli` 时，指定参数 `-D`
`-D<path>                - ZeroTier home path for parameter auto-detect`
```shell
root@EH-OPx86:~# zerotier-cli -D/var/lib/zerotier-luci/ info
200 info xxxxxxxx  1.12.1 ONLINE
```

2. 将文件 [`luci-app-zerotier/root/etc/init.d/luci_zerotier` 第八行 ](https://github.com/linkease/istore-packages/blob/3874e89f84c2036227ffb12007d12ba87befa188/luci-app-zerotier/root/etc/init.d/luci_zerotier#L8) 中 `zerotier-one` 配置路径变量 `CONFIG_PATH` 改回 `/var/lib/zerotier-one`

因为：
1. `zerotier-cli` 默认使用 `/var/lib/zerotier-one`
2. 其他开发者使用的路径均为 `/var/lib/zerotier-one`
  [Code search results: CONFIG_PATH=/var/lib/zerotier](https://github.com/search?q=CONFIG_PATH%3D%2Fvar%2Flib%2Fzerotier&type=code)
  ![image](https://github.com/linkease/istore-packages/assets/24244480/a698d7b9-2a7b-4deb-8c45-b66be67f9568)
  ![image](https://github.com/linkease/istore-packages/assets/24244480/1b1fd227-0e5f-4cce-9204-926ddacc95a5)
3. 虽然使用 `cli` 和 `luci` 界面配置 理念冲突，但是 web 界面查看状态啥的比较方便

**Comment by jjm2473** [comment]
路径是不可能改的，就是为了避免于zerotier默认的实例冲突才改成其他路径，zerotier有个启动脚本，zerotier_luci有另一个启动脚本，两个操作的路径不一样。如果你要使用/var/lib/zerotier-luci，又不想指定路径，那么开机时创建个软连接就行了，还有最好把zerotier启动脚本给disable掉。

**Comment by zctmdc** [comment]
[40_luci-zerotier#L12](https://github.com/linkease/istore-packages/blob/3874e89f84c2036227ffb12007d12ba87befa188/luci-app-zerotier/root/etc/uci-defaults/40_luci-zerotier#L12) 这个是安装后默认执行的么？ 已经 `disable` 了 

`/etc/init.d/zerotier disable`
