### ISSUE TITLE
期望 `luci-app-zerotier` 在新增网络时，可以自定义当前网络ID相关设置

### ISSUE THREAD

**Issue by zctmdc** [linkease/istore-packages#32]
## 需求

在使用 `zerotier-one` 时， 我们经常使用的功能就是自定义路由，例如

| 目标           | 网关         |
| -------------- | ------------ |
| 192.168.10.0/4 | 172.27.10.10 |
| 110.242.68.0/4 | 172.27.10.68 |

此时，我们需要

1.  [ZeroTier Central](https://my.zerotier.com/) 登录配置路由

2.  前往 `iStore` 商店安装 `zerotier` 客户端

3.  配置 `zerotier` 网络

此时 *192.168.10.0/4* 的网段，即可被映射到 *172.27.10.10*，
但是 *110.242.68.0/4* 的网段，还没被映射到 *172.27.10.68*。

## 问题

为什么 `zerotier` 无法自动配置 *110.242.68.0/4* 路由？

## 原因

`zerotier`  无法自动配置 *110.242.68.0/4* 路由，因为 *110.242.68.0/4*  不是 私有网段 [Private network wiki](https://en.wikipedia.org/wiki/Private_network)

### 方法一、 修改 [luci-app-zerotier](https://github.com/linkease/istore-packages/tree/main/luci-app-zerotier) 源码

- 前端

    - 状态页面
    
        **ZeroTier**

        Zerotier 是一个开源，跨平台，而且适合内网穿透互联的傻瓜配置虚拟 VPN LAN

        *Zerotier 运行中*
        
        | 启用  |   √   |
        | :---: | :---: |

        | network-id | allowManaged | allowGlobal | allowDefault | allowDNS |
        | :--------: | :----------: | :---------: | :----------: | :------: |
        |   xxxxxx   |      √       |      O      |      O       |    O     |
        |   yyyyyy   |      √       |      √      |      O       |    O     |

        | [------] | 添加  |
        | :------: | :---: |

    - 点击添加后
    
        *Zerotier 网络添加*
        |   网络 ID    | [xxxxxx] |
        | :----------: | :------: |
        | 允许私有网络 |    √     |
        | 允许公共网络 |    O     |
        | 允许默认网关 |    O     |
        |   允许 DNS   |    O     |

- 后端 
    在 [luci-app-zerotier/root/etc/init.d/luci_zerotier](https://github.com/linkease/istore-packages/blob/3874e89f84c2036227ffb12007d12ba87befa188/luci-app-zerotier/root/etc/init.d/luci_zerotier#L80) `add_join` 方法中 获取相关设置并保存到文件

    以下代码猜的

    ```shell
    local allow_managed
    local allow_global
    local allow_default
    local allow_dns
    network_setting_file=/var/lib/zerotier-luci/networks.d/$1.local.conf
    section_enabled allow_managed $1.allow_managed allow_managed 0
    [ "$allow_managed" -eq 0 ] && echo 'allowManaged=0' >> $network_setting_file
    section_enabled allow_global $1.allow_global allow_global 0
    [ "$allow_global" -eq 1 ] && echo 'allowGlobal=1' >> $network_setting_file
    section_enabled allow_default $1.allow_default allow_default 0
    [ "$allow_default" -eq 1 ] && echo 'allowDefault=1' >> $network_setting_file
    section_enabled allow_dns $1.allow_dns allow_dns 0
    [ "$allow_dns" -eq 1 ] && echo 'allowDNS=1' >> $network_setting_file
    ```

### 方法二、 编写脚本，手动配置 `zerotier`  客户端
    
1. 创建脚本文件夹
    
    ```shell
    mkdir -p /etc/config/zero/manual
    ```
    
2. 创建脚本文件
    1. 方案1
    
        ```shell
        cat > /etc/config/zero/manual/xxxxxx_allowGlobal.sh << EOF
        #!/bin/bash
        zerotier-cli -D/var/lib/zerotier-luci/ set xxxxxx allowGlobal=0
        EOF
        ```                                                                 
        
    2. 方案2
            
        ```shell
        cat <<- EOF > /etc/config/zero/manual/xxxxxx_allowGlobal.sh
        #!/bin/bash
        echo 'allowGlobal=1' >> /etc/config/zero/networks.d/xxxxxx.local.conf
        EOF
        ```

3. 设置脚本权限
    
```shell
chmod +x /etc/config/zero/manual/xxxxxx_allowGlobal.sh
```
    
4. 开机启动脚本
    
打开 系统 > 启动项 > 本地启动脚本
在 exit 0 前输入

```shell
sleep 60 && /etc/config/zero/manual/xxxxxx_allowGlobal.sh &
```

- 为什么要创建启动任务
    
    因为 [luci-app-zerotier/root/etc/init.d/luci_zerotier#L85](https://github.com/linkease/istore-packages/blob/3874e89f84c2036227ffb12007d12ba87befa188/luci-app-zerotier/root/etc/init.d/luci_zerotier#L85) 会在启动时删除所有的网络配置 

- `-D/var/lib/zerotier-luci/` 是什么

    [`luci-app-zerotier/root/etc/init.d/luci_zerotier` 第八行 ](https://github.com/linkease/istore-packages/blob/3874e89f84c2036227ffb12007d12ba87befa188/luci-app-zerotier/root/etc/init.d/luci_zerotier#L8) 中 `zerotier-one` 配置路径变量 `CONFIG_PATH` #31

### 参考

[zerotier 官方文档](https://docs.zerotier.com/config#network-specific-configuration)

**Comment by jjm2473** [comment]
zerotier的官网控制台不能设置这些参数吗？

**Comment by jjm2473** [comment]
openwrt的静态路由配置，能不能满足需求呢

**Comment by zctmdc** [comment]
> zerotier的官网控制台不能设置这些参数吗？

官网可以添加的  非私有网段 客户端需要配置 `allowGlobal`
![image](https://github.com/linkease/istore-packages/assets/24244480/38036c70-902d-4a9c-aada-4e370bece2e8)

> ## 原因
> zerotier 无法自动配置 110.242.68.0/4 路由，因为 110.242.68.0/4 不是 私有网段 [Private network wiki](https://en.wikipedia.org/wiki/Private_network)



> openwrt的静态路由配置，能不能满足需求呢

可以，但是

1.  `allowGlobal` 配置更加便捷
2. 官网后台配置后，需要手动同步每台客户端，容易忘记

**Comment by jjm2473** [comment]
我测试了下，allowDNS好像不能生效，可能是因为openwrt有自己的dns服务。

**Comment by jjm2473** [comment]
插件更新了，自己实现了个dns的处理脚本，现在可以支持你说的四个参数了。

PS：慎用默认网关，以免断网
